# User config
title: "Logo"
description: "Title"
subdescription: "Subtitle"

# Site config
baseurl: "/LessPhone"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
  
collections:
  days:
    output: true