# User config
description: "30 days of spending less time on the phone"
subdescription: "A diary"

# Site config
baseurl: "/LessPhone"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
  
collections:
  days:
    output: true